---
title: "R Notebook"
output: html_notebook
---

```{r, echo=F}

library(tidyr, quietly = T, warn.conflicts = F)
library(dplyr, quietly = T, warn.conflicts = F)
library(ggplot2)  
library(RColorBrewer)
library(stringr, quietly = T,warn.conflicts = F)
library(tidytext)
library(tidyselect)
library(tidyverse)
library(tm)
library(wordcloud)
library(data.table)
library(lettercase)



```


#Problem 1
I have created a new folder, Programming, and invited you as the collaborator for it.



#Problem 2
```{r, echo=F}
url <- 'https://raw.githubusercontent.com/stevewalsh124/STAT_5014/master/08_text_mining_Rnotebooks_bash_sed_awk/survey_data.txt'
survey_words <- read.delim(url, header = T, fill = T, stringsAsFactors = F)
survey_words

textDF1 <- data_frame(line=1:14, text = survey_words[,1])
textDF2 <- data_frame(line=1:14, text = survey_words[,2])
textDF3 <- data_frame(line=1:14, text = survey_words[,3])
textDF4 <- data_frame(line=1:14, text = survey_words[,4])
textDF  <- rbind(text_df1, text_df2, text_df3, text_df4)
textDF

newText <- textDF[,2]
newLower <- tolower(newText)
class(newText)


tidyText <- newLower  %>% 
    str_replace_all("ineer","") %>% str_replace_all("Eng", "engineer") %>% 
    str_replace_all("iate","") %>% str_replace_all("ermed","") %>% 
    str_replace_all("int","intermediate") %>% str_replace_all("inner","") %>% 
    str_replace_all("beg","beginner") %>% str_replace_all("some","") %>% 
    str_replace_all("just","") %>% str_replace_all("teeny","") %>% 
    str_replace_all("amount","") %>% str_replace_all("of","")  %>% 
    str_replace_all("surface","")


(tidyText)
tidyDF <- data_frame(text=tidyText)
finishedText <- tidyDF %>% unnest_tokens(word, text) %>% count(word, sort = T)


finishedText %>% with(wordcloud(word, n, min.freq = 1, max.words = 1500, colors=brewer.pal(8, "Dark2")))

finishedText %>% mutate(word = reorder(word, n)) %>% ggplot(aes(word, n)) + geom_col() + xlab(NULL) + ylab("Frequencies") + coord_flip()


```



#Problem 3
Of the three case studies at http://tidytextmining.com, I have chosen to examine the NASA case study data.  

```{r, echo=F}
library(jsonlite)
metadata <- fromJSON("https://data.nasa.gov/data.json")
names(metadata$dataset)

#Tidy the data up
nasa_title <- data_frame(id = metadata$dataset$`_id`$`$oid`, 
                         title = metadata$dataset$title)
nasa_title

nasa_desc <- data_frame(id = metadata$dataset$`_id`$`$oid`, 
                        desc = metadata$dataset$description)

nasa_desc %>% 
  select(desc) %>% 
  sample_n(5)

nasa_keyword <- data_frame(id = metadata$dataset$`_id`$`$oid`, 
                           keyword = metadata$dataset$keyword) %>%
  unnest(keyword)

nasa_keyword


nasa_title <- nasa_title %>% 
  unnest_tokens(word, title) %>% 
  anti_join(stop_words)

nasa_desc <- nasa_desc %>% 
  unnest_tokens(word, desc) %>% 
  anti_join(stop_words)

my_stopwords <- data_frame(word = c(as.character(1:10), 
                                    "v1", "v03", "l2", "l3", "l4", "v5.2.0", 
                                    "v003", "v004", "v005", "v006", "v7"))
nasa_title <- nasa_title %>% 
  anti_join(my_stopwords)
nasa_desc <- nasa_desc %>% 
  anti_join(my_stopwords)

nasa_keyword %>% 
  group_by(keyword) %>% 
  count(sort = TRUE)

nasa_keyword <- nasa_keyword %>% 
  mutate(keyword = toupper(keyword))

library(widyr)

title_word_pairs <- nasa_title %>% 
  pairwise_count(word, id, sort = TRUE, upper = FALSE)

title_word_pairs

library(ggplot2)
library(igraph)
library(ggraph)

set.seed(1234)
title_word_pairs %>%
  filter(n >= 250) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n), edge_colour = "cyan4") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE, 
                 point.padding = unit(0.2, "lines")) +
  theme_void()

##To do something different with this case study, I am going to create a word cloud to examine how often words are used

library(wordcloud)
library(SnowballC)


#I'm having trouble getting this wordcloud to work like the other one did
nasa_keyword %>% with(wordcloud(word, n, min.freq = 1, max.words = 1500, colors=brewer.pal(8, "Dark2")))



```



#Problem 4
I have successfully created a login at arc.vt.edu and logged in. 



#Problem 5
If you are reading this, then the homework was successfully pushed to GitHub.




